AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: raisetech-practice
  
  Public1a:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: raisetech-practice-public1a

  Public1c:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.3.0/24
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: raisetech-practice-public1c

  Private1a:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: raisetech-practice-private1a

  Private1c:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: raisetech-practice-private1c

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: raisetech-practice-igw
        
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: raisetech-practice-route

  RouteLocal21a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Public1a
      RouteTableId: !Ref RouteTable
  
  RouteLocal21c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref Public1c
      RouteTableId: !Ref RouteTable
    
  route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: raisetech-practice-sg-for-public
      GroupDescription: This SecurityGroup is for PracticePublicSecurityGroup
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: raisetech-practice-sg-for-public

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: raisetech-practice-sg-for-rds
      GroupDescription: This SecurityGroup is for PracticePrivateSecurityGroup
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: raisetech-practice-sg-for-rds

  EC2InstancePublic1a:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: jenkins
      DisableApiTermination: false
      ImageId: ami-09d28faae2e9e7138
      InstanceType: t2.micro
      SubnetId: !Ref Public1a
      Monitoring: false
      AvailabilityZone: ap-northeast-1a
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      UserData: !Base64 
        #!/bin/bash -ex
        # put your script here
        sudo yum update -y
      Tags:
        - Key: Name
          Value: raisetech-practice-ec2-1a

  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: This DBsubnet Group is for AWSNEWProjectRDS
      SubnetIds:
        - !Ref Private1a
        - !Ref Private1c
      Tags:
        - Key: Name
          Value: raisetech-practice-subnet-group-1a-1c
  
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups: 
        - !Ref PrivateSecurityGroup
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      EngineVersion: 8.0.20
      MasterUsername: jenkins
      MasterUserPassword: jenkins0410

